### ISSUE TITLE
[Discussion] The `event:` scheme and threads

### ISSUE THREAD

**Issue by jD91mZM2** [redox-os/kernel#89]
### Situation

Currently each thread has it's own event queue (they're per context), just like a process.
Things like Tokio need to share one event queue between threads.

### Proposed solutions

 - Do nothing. Tokio can be patched by making mio do everything from one thread. [Example can be seen here](https://github.com/jD91mZM2/mio/commit/dbac7eb0dbcb0f649e5e0c468c47d8cab48dc821). This almost works actually, woah. Would be extremely inefficient though. This would be backwards compatible because nothing would actually be done.
 - Make them share event queues. I think this would be the easiest way, since threads already share memory somehow. Although this means that it's now impossible for one process to host multiple `event:` instances. Would be a minor change.
 - Change `fevent` to be a scheme function like `fcntl`. This would allow it to sit per-instance rather than per-context. Actually - I'm not sure this would work. Depends on if open files are shared between threads. Would not be backwards compatible.
 - Change `event:` to take an ID. This would also need a syscall for generating an ID, and `fevent` would need to take this ID as an instance. Would not be backwards compatible.

Once a decision is made, is it within my scope of RSoC to adjust the kernel myself, or is it up to whoever is first?

**Comment by ids1024** [comment]
> Make them share event queues. I think this would be the easiest way, since threads already share memory somehow. Although this means that it's now impossible for one process to host multiple event: instances. Would be a minor change.

Sharing memory and such depends on the arguments to `syscall:clone`: https://github.com/rust-lang/rust/blob/master/src/libstd/sys/redox/thread.rs

Perhaps this should have it's own `*_CLONE` constant? Probably, though it doesn't necessary change much since it would still always be set (or not) when creating a thread though the standard library.

**Comment by tbodt** [comment]
I'm not a fan of the idea of sharing event queues. Event queues should be objects that you can create as many as you need, not thread or process specific attributes. I'm pretty sure every other operating system does it that way.

**Comment by jackpot51** [comment]
It could certainly be done that way @tbodt

**Comment by jD91mZM2** [comment]
What about the `fcntl` scheme function? Might be a little misleading, but it is unused for `event:` and it sort of makes sense that you register an I/O by configuring an event instance. Would also have the benefit of the current scheme id system so it seems like it'd be easy enough as well :D

**Comment by jD91mZM2** [comment]
I just had a go at implementing this and it went horrible because the `fevent` scheme function still needs to exist in order to notify schemes that it should start producing events. But then I think that means that the syscall needs to stay which means we still need to register AAAAND in the end nothing has changed

**Comment by jD91mZM2** [comment]
... tried to patch the kernel... again.
... and got stuck... again.

This time the issue is that adding an `onto`/`instance` parameter doesn't actually let you know what event queue it is because they're registered by ID, not by file descriptor. And the `open` call can't possibly know about the file descriptor either.

**Comment by jackpot51** [comment]
Please take a look here: https://github.com/redox-os/rfcs/pull/10

This is what I intend to implement: https://github.com/redox-os/rfcs/blob/event-overhaul/text/0000-event-overhaul.md#detailed-design

**Comment by jD91mZM2** [comment]
@jackpot51 Nice, okay, huge thanks! Seems almost like the `fcntl` idea but way better! Main issue I got with that idea was that something was still calling `fevent` but grep didn't show me anything what so ever. Is there a way to show information about the caller from a syscall so I know what old code needs patching?

**Comment by jackpot51** [comment]
You can turn on debugging in kernel/src/syscall/mod.rs

**Comment by jD91mZM2** [comment]
Closed by https://github.com/redox-os/kernel/commit/99a3bff2dae706ab1ca0548093620fbd2d9732d3 :tada:
